name: Tests
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    # 16:21 UTC on Tuesdays
    - cron: "21 16 * * TUE"
  repository_dispatch:
    types: [tests]

# https://doc.rust-lang.org/cargo/guide/continuous-integration.html
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install just
        run: sudo apt install -y just
      - name: Build
        run: cargo build --all-targets
      - name: Test & lint
        run: just --color=always validate
